### PR TITLE
Version 1.1.5

### PR DESCRIPTION
**Pull request by bjfultn**
- added celerite GP kernel
- added new example using the celerite kernel
- added .readthedocs.yml and separate requirements file for RTD
- added numerical prior

### CODE REVIEW

**Comment by bjfultn** [comment]
@sblunt could you add a test for this prior in `test_api.test_priors`? Please work directly on the `next-release` branch.

**Comment by sblunt** [comment]
Done.

**Comment by bjfultn** [comment]
@sblunt I don't see any changes to `test_api.py` in your recent commit?

**Comment by sblunt** [comment]
Sorry, looks like my internet connection wigged out during my last push and stuff didn't actually get uploaded. Should be fixed now.

**Pull request merged**
