### PR TITLE
Gp api

### PR DESCRIPTION
**Pull request by petigura**

### CODE REVIEW

**Comment by petigura** [comment]
@sblunt: GPI API looks like it's off to a good start: Some comments.

1. Seems like there is a mix of tabs and comments: Let's try to maintain compliance with PEP8 style with 4 spaces per indent. Here's an example

```
       def __init__(self, params, covmatrix=None):
		self.covmatrix = covmatrix
		for par in params:
```
2. `length` is defined twice in several GPs

```
	def __init__(self, params, covmatrix=None):
 +		self.covmatrix = covmatrix
 +		for par in params:
 +			if par.startswith('length'):
 +				self.length = params[par].value
 +			if par.startswith('amp'):
 +				self.amp = params[par].value
 +			if par.startswith('length'):
 +				self.length = params[par].value
 +
```

3. Do we want to adopt consistent nomenclature for GP parameters, i.e. `gp_length`?

4. Would like to see an example of using the GP API.

**Comment by petigura** [comment]
FYI: Python3 enforces the no tabs rule:

image

**Comment by sblunt** [comment]
Thanks for the comments, @petigura! First three comments will been addressed in my next commits. I'm going to wait to make an example config file until I have the GP likelihood code done, but hopefully that will be finished before Monday.

**Comment by bjfultn** [comment]
@sblunt running the Kepler21_GP.py file raises an exception for me:
```
kapua:analysis bfulton$ python ~/code/radvel/example_planets/Kepler21_GP.py
/Users/bfulton/anaconda/lib/python2.7/site-packages/radvel/orbit.py:35: RuntimeWarning: invalid value encountered in sqrt
  EE = 2 * np.arctan( np.tan(f/2) * np.sqrt((1-ecc)/(1+ecc)) )  # eccentric anomaly
Traceback (most recent call last):
  File "/Users/bfulton/code/radvel/example_planets/Kepler21_GP.py", line 50, in <module>
    res = optimize.minimize(gppost.neglogprob_array, gppost.get_vary_params(), method="Powell")
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/scipy/optimize/_minimize.py", line 477, in minimize
    return _minimize_powell(fun, x0, args, callback, **options)
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 2572, in _minimize_powell
    tol=xtol * 100)
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 2365, in _linesearch_powell
    alpha_min, fret, iter, num = brent(myfunc, full_output=1, tol=tol)
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 2076, in brent
    res = _minimize_scalar_brent(func, brack, args, **options)
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 2108, in _minimize_scalar_brent
    brent.optimize()
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 1892, in optimize
    xa, xb, xc, fa, fb, fc, funcalls = self.get_bracket_info()
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 1866, in get_bracket_info
    xa, xb, xc, fa, fb, fc, funcalls = bracket(func, args=args)
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 2297, in bracket
    fc = func(*((xc,) + args))
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 2364, in myfunc
    return func(p + alpha*xi)
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/radvel/likelihood.py", line 92, in neglogprob_array
    return -self.logprob_array(params_array)
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/radvel/posterior.py", line 80, in logprob_array
    _logprob = self.logprob()
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/radvel/posterior.py", line 47, in logprob
    _logprob = self.likelihood.logprob()
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/radvel/likelihood.py", line 317, in logprob
    alpha = cho_solve(cho_factor(K),r)
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/scipy/linalg/decomp_cholesky.py", line 174, in cho_solve
    b1 = asarray_chkfinite(b)
  File "/Users/bfulton/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1215, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```
Should I be able to run this file right now? If so, lets make a test function for it so that the CI would catch this bug.

**Comment by sblunt** [comment]
Working on it!

**Comment by sblunt** [comment]
Fixed.

**Pull request closed without merging**
