### PR TITLE
Support for additional `celerite` kernels

### PR DESCRIPTION
**Pull request by vandalt**
Hello,

As discussed in #353, I implemented the `Matern32Term` and `SHOTerm` from celerite within the RadVel gp framework. This PR contains:

- Tests for celerite kernels (comparing with the outputs of a celerite object)
- An abtract class for celerite kernels that has some of the code common to all celerite kernels
- Methods to calculate the covariance matrix of celerite kernel (mainly useful for testing, but also uniformizes the GP interface between celerite and other kernels)
- New kernel classes for Matern 3/2 and SHO terms
- `CeleriteLiklihood.predict()` is now more general to support other celerite kernels

I saw that there is a [gp-multiply-kernels](https://github.com/California-Planet-Search/radvel/tree/gp-multiply-kernels) branch, so I was wondering if I should rebase against this one instead of master ?

Thank you!

### CODE REVIEW

**Comment by vandalt** [comment]
Converted to draft because I just realized there is a bug when `Q < 0.5` because the real terms are array. I'll try to use the (unused) `1`and `3`indices of `CeleriteKernel.real` to work around that.

**Comment by vandalt** [comment]
The issue with `Q < 0.5` is now fixed, I added a test covering this as well.

**Comment by vandalt** [comment]
Marked as draft to rebase on #359, which refactors the GP API.

**Comment by bjfultn** [comment]
Is this still a WIP?

**Comment by sblunt** [comment]
Yeah, we'll need to reimplement the celerite functionality based on the tinygp refactor in #363

**Comment by vandalt** [comment]
Unfortunately could not work on this lately. I'm hoping to have time this winter, but in the meantime anyone feel free to take over!

**Pull request closed without merging**
