### PR TITLE
update planet_parameters with change of basis

### PR DESCRIPTION
**Pull request by megbedell**
Make sure that the `planet_parameters` attribute of a Parameters instance matches the chosen basis even after transforming.

This is a fix to the following bug:

```
params = radvel.model.Parameters(2, basis='per tp e w k')
# set some parameter values here
synth_basis = radvel.basis.Basis(params.basis.name, params.num_planets)
mcmc_params = synth_basis.from_synth(params, 'logper tc secosw sesinw logk', keep=False)
print(mcmc_params.planet_parameters)
```

would formerly return the old basis (`per tp e w k`) instead of the updated basis (`logper tc secosw sesinw logk`).
(At least I think that's a bug -- unless I'm misunderstanding the desired behavior?)

### CODE REVIEW

**Comment by bjfultn** [comment]
This does indeed look like a bug. Thank you for the contribution @megbedell!

**Comment by bjfultn** [comment]
I changed the base to `next-release`, can you pull/merge `next-release` into your branch to make sure its up to date?

**Comment by megbedell** [comment]
@bjfultn I did the following, is that sufficient or do I need to move the edits that I made in my fork's default branch to the `next-release` branch and update the PR? Sorry, I'm not the best with github!

```
(radvel) Megans-Work-Laptop:radvel mbedell$ git checkout next-release
Branch next-release set up to track remote branch next-release from origin.
Switched to a new branch 'next-release'
(radvel) Megans-Work-Laptop:radvel mbedell$ git status
On branch next-release
Your branch is up-to-date with 'origin/next-release'.
nothing to commit, working tree clean
```

**Comment by bjfultn** [comment]
Looks like you are good. Now we just wait for the tests to run...

**Pull request merged**
