### PR TITLE
Pull gp-api into next-release

### PR DESCRIPTION
**Pull request by sblunt**
Travis is backed up and my builds are all timing out. I'll wait until tomorrow to see if I can get my build to work. All of the tests are passing in my computer's python3 and python2 environments.

### CODE REVIEW

**Comment by petigura** [comment]
Is there an easy fix like decreasing the number of chains to run?

Erik

**Comment by sblunt** [comment]
I've tried cutting down the number of chains and iterations as much as possible. I'll look into it more later today, but I think there are some other weird Travis problems.

**Comment by bjfultn** [comment]
Keep in mind that I added tests for the Jupiter notebooks here too. So you'll need to reduce those chains as well.

**Comment by sblunt** [comment]
Ok, I think I maybe figured it out. Testing now.

**Comment by bjfultn** [comment]
Looks good, thanks @sblunt!

**Pull request merged**
