### PR TITLE
Version 1.1.8

### PR DESCRIPTION
**Pull request by bjfultn**
- switch back to Powell minimizer and expose as an option in response to issue #164 
- removed most deepcopy calls in response to issue #166 
- made celerite an optional dependency in response to issue #162 
- fixed bug in celerite setup file

### CODE REVIEW

**Comment by bjfultn** [comment]
@sblunt it looks like we are running into issues with the AC>=BD constraint in Celerite. Possibly due to switching back to the Powell minimization method. Is there a way around this? Or will we need to use the Nelder-Mead minimizer when using the Celerite GP?

This is causing the failure in pull request #165 as well.

**Comment by sblunt** [comment]
Yeah, I was worried about that. I'm planning to fix it in the next version. It's a deeper problem that using the Nelder-Mead minimization was patching put not actually fixing. For now, I suggest taking the celerite kernel out of RadVel completely until I get a chance to implement the updated version. Does that sound ok? I don't think anyone is using it yet, so I don't think that will be a problem.

**Comment by bjfultn** [comment]
@sblunt The fix turned out to be really easy actually. The K2-131_celerite setup file was starting the ft with
```
params['2_logB'] = radvel.Parameter(value=np.log(0.0), vary=False)
params['2_logD'] = radvel.Parameter(value=np.log(0.0), vary=False)
```
which is undefined and the minimizer was not allowed to move those parameters. Changing the starting point of those parameters allows the fit to proceed without crashing. We still get warning messages when the minimizer tries to explore disallowed regions but the fit proceeds and looks reasonable.

**Comment by sblunt** [comment]
Oh ok great! Thanks for catching that.

**Pull request merged**
