### PR TITLE
Version 2 - MCMC Overhaul

### PR DESCRIPTION
**Pull request by bjfultn**
@pdn4kd I pulled this into the primary repo to test and prepare for merging.

### CODE REVIEW

**Comment by bjfultn** [comment]
@pdn4kd It looks like this is significantly slower than the current implementation. Saving the progress plots and chains does slow it down a bit, but the main slowdown is due to the removal of the simultaneous parallel ensembles. It seems like running in `--serial` mode is actually a little faster than allowing emcee to use multiple processes. Why was the existing parallelization scheme removed?

**Comment by pdn4kd** [comment]
The only API-related changes should be in the mcmc function specifically, at its switch from G-R to autocorrelation.

For the performance issue, Peter moved the parallelization into Emcee, though this only works with the v3.0rc2 version at the moment.
https://emcee.readthedocs.io/en/latest/user/sampler/
https://emcee.readthedocs.io/en/latest/tutorials/parallel/#parallel

**Comment by bjfultn** [comment]
The problem is that the `emcee3` parallelization is extremely inefficient. It seems to utilize ~3 cores when running 8 ensembles and actually slows things down relative to running single-threaded. I think that the built-in parallelization is designed for likelihoods which take a long time to calculate (several seconds or more). 

However, I don't necessarily know how to define a good autocorrelation-based convergence criteria if we go back to our multiple fully-independent ensemble scheme for parallelization. Can we calculate these statistics across multiple ensembles?

**Comment by plavchan** [comment]
BJ - You're correct. I've got a 6-core machine and 8-core cluster nodes, and it was generally tapping out at ~3 cores each, but I was also running two jobs per machine.  

There's no reason why you can't re-do the parallelization that existed in the current code.  It will not affect the autocorrelation time, with the exception that the convergence check will have to loop over all sets of samplers instead of just the one, and you can turn off the parallelization in the emceesampler.  Then you will have multiple backends, one for each sampler. This will also turn bottleneck the parallelization with the disk I/O.  I'm not sure how much it would bottleneck.  I did have a version working like that at one point.

I think if you retain the parallelization in your code, that will provide more flexibility for people running things on 10-core CPUs.

Generally speaking, I would say different applications can be optimized differently:  <~10 parameters,~1-2 planets - probably more efficient with keeping the chains in memory.  Generally also I would say >~10 parameters aka 3 or more planets - it's definitely more efficient to store the chains on disk.  While overall the steps/sec is slower, we saw chain memory sizes exceeding 20GB with the existing radvel code, and crashing as a a result quite often, particularly with >=5 planets and associated free parameters.  It would make sense in the next version of radvel (timed with the release of emcee3.0) to support a flag to either store the chains in memory, or store on disk, given the different use cases and optimizations for speed of computation.

The convergence check for the autocorrelation time is max(auto-correlation of each walker). So, it's relatively easy to extend that across multiple samplers in parallel, and you basically stop when all samplers have converged with the max(auto-correlation over all samplers and walkers).

**Comment by bjfultn** [comment]
> The convergence check for the autocorrelation time is max(auto-correlation of each walker). So, it's relatively easy to extend that across multiple samplers in parallel, and you basically stop when all samplers have converged with the max(auto-correlation over all samplers and walkers).

It sounds like we wouldn't actually reach convergence any faster because this statistic is a property of each walker. Running independent ensembles will allow us to calculate more steps/s overall, but any one walker will take the same number of steps/s.

> It would make sense in the next version of radvel (timed with the release of emcee3.0) to support a flag to either store the chains in memory, or store on disk, given the different use cases and optimizations for speed of computation.

This is certainly easy enough to do. I also really like the ability to save the progress of the chains as we go, and I'd like to be able to continue the fit where it left off if interrupted.

You also raised a good point here that we can't release this version until emcee3 is officially released, we will also probably have to drop Python 2 support at that time (assuming emcee3 is py3 only) so we will probably increment to version 2.0.

**Comment by bjfultn** [comment]
Update on this: I'm thinking about incorporating the low-level parts of DFM's `exoplanets` package into radvel and using Pymc3 for the MCMC so that we can take advantage of modern techniques like autodiff and the NUTS sampling algorithm. I'm meeting with DFM this week to talk about this.

**Comment by bjfultn** [comment]
All of this functionality has finally been incorporated into RadVel 1.3.1! Thank you @plavchan and @pdn4kd! We didn't end up using most of this code, but @spencer3616 relied on it as a template to add these improvements in a way that retained multi-processing.

**Pull request closed without merging**
